name: verifica_notas

on:
  schedule:
    - cron: '*/5 * 15-20 07 *' # A cada 5 minutos entre os dias 15 e 20 de julho
  push:
  workflow_dispatch:


jobs:
  verifica_notas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache grades
        id: cache-grades
        uses: actions/cache@v3
        with:
            path: grades.json
            key: ${{ runner.os }}-cache-grades-${{ github.run_id }}
            restore-keys: |
              ${{ runner.os }}-cache-grades
      - name: Build container
        run: docker build --tag ansiac .
      - name: run container
        env:
          DYNACONF_SIAC__USERNAME: ${{ secrets.DYNACONF_SIAC__USERNAME }}
          DYNACONF_SIAC__PASSWORD: ${{ secrets.DYNACONF_SIAC__PASSWORD }}
          DYNACONF_TELEGRAM__BOT_TOKEN: ${{ secrets.DYNACONF_TELEGRAM__BOT_TOKEN }}
          DYNACONF_TELEGRAM__CHAT_ID: ${{ secrets.DYNACONF_TELEGRAM__CHAT_ID }}
        run: |
          docker run \
            --volume $(pwd):/app \
            --env DYNACONF_SIAC__USERNAME \
            --env DYNACONF_SIAC__PASSWORD \
            --env DYNACONF_TELEGRAM__BOT_TOKEN \
            --env DYNACONF_TELEGRAM__CHAT_ID \
            ansiac