name: verifica_notas

on:
  schedule:
    - cron: '0 * * * *'
  push:

jobs:
  verifica_notas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build container
        run: docker build --tag ansiac .
      - name: run container
        env:
          DYNACONF_SIAC_USERNAME: ${{ secrets.DYNACONF_SIAC_USERNAME }}
          DYNACONF_SIAC_PASSWORD: ${{ secrets.DYNACONF_SIAC_PASSWORD }}
          DYNACONF_TELEGRAM_BOT_TOKEN: ${{ secrets.DYNACONF_TELEGRAM_BOT_TOKEN }}
          DYNACONF_TELEGRAM_CHAT_ID: ${{ secrets.DYNACONF_TELEGRAM_CHAT_ID }}
        run: |
          docker run \
            --volume $(pwd):/app \
            --env DYNACONF_SIAC_USERNAME \
            --env DYNACONF_SIAC_PASSWORD \
            --env DYNACONF_TELEGRAM_BOT_TOKEN \
            --env DYNACONF_TELEGRAM_CHAT_ID \
            ansiac